[Thu Oct 10 07:35:01.759674 2019] [wsgi:warn] [pid 26641:tid 140555675871104] mod_wsgi: Compiled for Python/2.7.11.
[Thu Oct 10 07:35:01.759691 2019] [wsgi:warn] [pid 26641:tid 140555675871104] mod_wsgi: Runtime using Python/2.7.12.
[Thu Oct 10 07:35:01.760040 2019] [mpm_event:notice] [pid 26641:tid 140555675871104] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Thu Oct 10 07:35:01.760052 2019] [core:notice] [pid 26641:tid 140555675871104] AH00094: Command line: '/usr/sbin/apache2'
[Thu Oct 10 08:41:40.497371 2019] [wsgi:error] [pid 31062:tid 140555483674368] \x1b[93m Simulacion en Websim con usuario no registrado. Cargando plantilla de codigo por defecto /var/www/kibotics/jderobot_server/exercises/scratch/siguelinea_pibot_scratch_vision/siguelinea_pibot_scratch_vision.xml\x1b[0m
[Thu Oct 10 08:41:40.498133 2019] [wsgi:error] [pid 31062:tid 140555483674368] /usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py:101: Warning: (1364L, u"Field 'main_server_ip' doesn't have a default value")
[Thu Oct 10 08:41:40.498144 2019] [wsgi:error] [pid 31062:tid 140555483674368]   return self.cursor.execute(query, args)
[Thu Oct 10 09:04:50.016129 2019] [wsgi:error] [pid 31062:tid 140555483674368] \x1b[93m Simulacion en Websim con usuario no registrado. Cargando plantilla de codigo por defecto /var/www/kibotics/jderobot_server/exercises/scratch/siguelinea_pibot_scratch_vision/siguelinea_pibot_scratch_vision.xml\x1b[0m
[Thu Oct 10 09:06:38.583399 2019] [wsgi:error] [pid 31062:tid 140555483674368] \x1b[93m Simulacion en Websim con usuario no registrado. Cargando plantilla de codigo por defecto /var/www/kibotics/jderobot_server/exercises/scratch/siguelinea_pibot_scratch_vision/siguelinea_pibot_scratch_vision.xml\x1b[0m
[Thu Oct 10 09:16:32.647307 2019] [wsgi:error] [pid 31062:tid 140555483674368] \x1b[93m Simulacion en Websim con usuario no registrado. Cargando plantilla de codigo por defecto /var/www/kibotics/jderobot_server/exercises/scratch/siguelinea_pibot_scratch_vision/siguelinea_pibot_scratch_vision.xml\x1b[0m
[Thu Oct 10 10:04:09.113946 2019] [wsgi:error] [pid 31062:tid 140555128215296] /usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
[Thu Oct 10 10:04:09.113995 2019] [wsgi:error] [pid 31062:tid 140555128215296]   self._cipher = factory.new(key, *args, **kwargs)
[Thu Oct 10 10:04:09.927697 2019] [wsgi:error] [pid 31062:tid 140555391354624] La carpeta /var/lib/jderobot/Academy-Farm/users/admin/ ya existe en la maquina f-l3209-pc10.kibotics.org
[Thu Oct 10 10:04:10.653526 2019] [wsgi:error] [pid 31062:tid 140555391354624] La carpeta /var/lib/jderobot/Academy-Farm/users/admin/introduccion_python/ ya existe en la maquina f-l3209-pc10.kibotics.org
[Thu Oct 10 10:04:19.612685 2019] [wsgi:error] [pid 31062:tid 140555391354624] 11.4361670017
[Thu Oct 10 10:16:34.657458 2019] [wsgi:error] [pid 31062:tid 140555391354624] 404 {u'documentation_url': u'https://developer.github.com/v3/repos/contents/#get-contents', u'message': u'Not Found'}
[Thu Oct 10 10:16:34.657489 2019] [wsgi:error] [pid 31062:tid 140555391354624] \x1b[93m No existen archivos de la practica cuadrado_drone_scratch del usuario ralvarezmar en el repositorio. Copiando archivos por defecto.\x1b[0m
[Thu Oct 10 10:30:27.867596 2019] [wsgi:error] [pid 31062:tid 140555391354624] 404 {u'documentation_url': u'https://developer.github.com/v3/repos/contents/#get-contents', u'message': u'Not Found'}
[Thu Oct 10 10:30:27.867625 2019] [wsgi:error] [pid 31062:tid 140555391354624] \x1b[93m No existen archivos de la practica cuadrado_drone_scratch del usuario ralvarezmar en el repositorio. Copiando archivos por defecto.\x1b[0m
[Thu Oct 10 11:41:26.564822 2019] [mpm_event:notice] [pid 26641:tid 140555675871104] AH00493: SIGUSR1 received.  Doing graceful restart
[Thu Oct 10 11:41:26.667947 2019] [wsgi:warn] [pid 26641:tid 140555675871104] mod_wsgi: Compiled for Python/2.7.11.
[Thu Oct 10 11:41:26.667957 2019] [wsgi:warn] [pid 26641:tid 140555675871104] mod_wsgi: Runtime using Python/2.7.12.
[Thu Oct 10 11:41:26.668622 2019] [mpm_event:notice] [pid 26641:tid 140555675871104] AH00489: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Thu Oct 10 11:41:26.668649 2019] [core:notice] [pid 26641:tid 140555675871104] AH00094: Command line: '/usr/sbin/apache2'
[Thu Oct 10 11:43:37.481945 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc01.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58adb6c90>, 'Connection to f-l3208-pc01.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:43:37.481996 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc01.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:44:06.051195 2019] [wsgi:error] [pid 15922:tid 140555492067072] /usr/local/lib/python2.7/dist-packages/django/db/backends/mysql/base.py:101: Warning: (1364L, u"Field 'main_server_ip' doesn't have a default value")
[Thu Oct 10 11:44:06.051211 2019] [wsgi:error] [pid 15922:tid 140555492067072]   return self.cursor.execute(query, args)
[Thu Oct 10 11:44:35.071400 2019] [wsgi:error] [pid 15922:tid 140555382961920] 404 {u'documentation_url': u'https://developer.github.com/v3/repos/contents/#get-contents', u'message': u'Not Found'}
[Thu Oct 10 11:44:35.071432 2019] [wsgi:error] [pid 15922:tid 140555382961920] \x1b[93m No existen archivos de la practica siguelinea_f1_scratch_vision del usuario admin en el repositorio. Copiando archivos por defecto.\x1b[0m
[Thu Oct 10 11:44:37.605782 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc02.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58aca1a50>, 'Connection to f-l3208-pc02.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:44:37.605811 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc02.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:45:37.729526 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc03.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58aca1a90>, 'Connection to f-l3208-pc03.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:45:37.729557 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc03.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:46:37.859397 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc04.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58aafebd0>, 'Connection to f-l3208-pc04.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:46:37.859429 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc04.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:47:35.509211 2019] [wsgi:error] [pid 15923:tid 140555371648768] [client 193.147.79.191:45334] Timeout when reading response headers from daemon process 'kibotics': /var/www/kibotics/jderobot_server/jderobot_server/wsgi.py
[Thu Oct 10 11:47:37.963876 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc05.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58ab3add0>, 'Connection to f-l3208-pc05.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:47:37.963905 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc05.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:48:38.119972 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc06.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58aafeb50>, 'Connection to f-l3208-pc06.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:48:38.120005 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc06.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:49:38.226697 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc07.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58ab0ef10>, 'Connection to f-l3208-pc07.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:49:38.226728 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc07.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:50:38.331243 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc08.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58ab4e410>, 'Connection to f-l3208-pc08.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:50:38.331275 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc08.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:51:38.490921 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc09.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58aa991d0>, 'Connection to f-l3208-pc09.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:51:38.491030 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc09.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:52:38.586798 2019] [wsgi:error] [pid 15922:tid 140555374569216] HTTPConnectionPool(host='f-l3208-pc10.kibotics.org', port=2375): Max retries exceeded with url: /v1.35/containers/json?all=1&limit=-1&filters=%7B%22ancestor%22%3A+%5B%22kibotics%2Fsimulation%3Abionic%22%5D%2C+%22name%22%3A+%5B%22admin%5C%5C-%28%5BA-z%5D%2B%29%2B%5C%5C-%2B%28%5B0-9%5D%2B%5C%5C.%2B%5B0-9%5D%2B%29%22%5D%7D&trunc_cmd=0&size=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd58aa99350>, 'Connection to f-l3208-pc10.kibotics.org timed out. (connect timeout=60)'))
[Thu Oct 10 11:52:38.586831 2019] [wsgi:error] [pid 15922:tid 140555374569216] \x1b[91mNo ha sido posible establecer con el Cliente de Docker de f-l3208-pc10.kibotics.org (TimeOut Error).\x1b[0m
[Thu Oct 10 11:52:39.333593 2019] [wsgi:error] [pid 15922:tid 140555374569216] [remote 193.147.79.191:1451] mod_wsgi (pid=15922): Exception occurred processing WSGI script '/var/www/kibotics/jderobot_server/jderobot_server/wsgi.py'.
[Thu Oct 10 11:52:39.333658 2019] [wsgi:error] [pid 15922:tid 140555374569216] [remote 193.147.79.191:1451] IOError: failed to write data
[Thu Oct 10 12:31:14.912267 2019] [wsgi:error] [pid 15922:tid 140555131098880] /usr/lib/python2.7/dist-packages/Crypto/Cipher/blockalgo.py:141: FutureWarning: CTR mode needs counter parameter, not IV
[Thu Oct 10 12:31:14.912321 2019] [wsgi:error] [pid 15922:tid 140555131098880]   self._cipher = factory.new(key, *args, **kwargs)
[Thu Oct 10 12:31:15.703150 2019] [wsgi:error] [pid 15922:tid 140555492067072] La carpeta /var/lib/jderobot/Academy-Farm/users/admin/ ya existe en la maquina f-l3209-pc10.kibotics.org
[Thu Oct 10 12:31:16.393378 2019] [wsgi:error] [pid 15922:tid 140555492067072] La carpeta /var/lib/jderobot/Academy-Farm/users/admin/cuadrado_tello/ ya existe en la maquina f-l3209-pc10.kibotics.org
[Thu Oct 10 12:31:20.279775 2019] [wsgi:error] [pid 15922:tid 140555492067072] 6.51767086983
[Thu Oct 10 14:13:14.547630 2019] [wsgi:error] [pid 15922:tid 140555492067072] 14.1809830666
[Thu Oct 10 22:50:59.988257 2019] [wsgi:error] [pid 15922:tid 140555492067072] \x1b[93m Simulacion en Websim con usuario no registrado. Cargando plantilla de codigo por defecto /var/www/kibotics/jderobot_server/exercises/scratch/siguelinea_pibot_scratch_vision/siguelinea_pibot_scratch_vision.xml\x1b[0m
[Fri Oct 11 07:35:01.666592 2019] [mpm_event:notice] [pid 26641:tid 140555675871104] AH00493: SIGUSR1 received.  Doing graceful restart